# Generated by Django 3.2.7 on 2021-09-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='prd',
            new_name='prod',
        ),
    ]
