# Generated by Django 3.2.7 on 2023-06-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartlist_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='created_by',
            new_name='user_id',
        ),
    ]
